const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: '123456',
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: '123456',
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    // Hoodies (5-9)
    {
      // _id: '5',
      name: 'Champion Classic Hoodie',
      slug: 'champion-classic-hoodie',
      category: 'Hoodies',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 12,
      brand: 'Champion',
      rating: 4.3,
      numReviews: 18,
      description: 'Comfortable cotton blend hoodie with front pocket',
    },
    {
      // _id: '6',
      name: 'Nike Tech Fleece Hoodie',
      slug: 'nike-tech-fleece-hoodie',
      category: 'Hoodies',
      image: '/images/p6.jpg',
      price: 110,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 24,
      description: 'Lightweight tech fleece for ultimate comfort',
    },
    {
      // _id: '7',
      name: 'Adidas Trefoil Hoodie',
      slug: 'adidas-trefoil-hoodie',
      category: 'Hoodies',
      image: '/images/p7.jpg',
      price: 85,
      countInStock: 9,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 16,
      description: 'Classic trefoil logo hoodie in soft cotton',
    },
    {
      // _id: '8',
      name: 'Under Armour Storm Hoodie',
      slug: 'under-armour-storm-hoodie',
      category: 'Hoodies',
      image: '/images/p8.jpg',
      price: 75,
      countInStock: 14,
      brand: 'Under Armour',
      rating: 4.2,
      numReviews: 12,
      description: 'Water-resistant hoodie with thermal insulation',
    },
    {
      // _id: '9',
      name: 'Puma Essential Hoodie',
      slug: 'puma-essential-hoodie',
      category: 'Hoodies',
      image: '/images/p9.jpg',
      price: 60,
      countInStock: 20,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 15,
      description: 'Essential everyday hoodie with classic styling',
    },
    // Shirts (10-14)
    {
      // _id: '10',
      name: 'Ralph Lauren Oxford Shirt',
      slug: 'ralph-lauren-oxford-shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 95,
      countInStock: 8,
      brand: 'Ralph Lauren',
      rating: 4.7,
      numReviews: 22,
      description: 'Classic oxford button-down in premium cotton',
    },
    {
      // _id: '11',
      name: 'Tommy Hilfiger Dress Shirt',
      slug: 'tommy-hilfiger-dress-shirt',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 85,
      countInStock: 11,
      brand: 'Tommy Hilfiger',
      rating: 4.5,
      numReviews: 17,
      description: 'Non-iron dress shirt for professional settings',
    },
    {
      // _id: '12',
      name: 'Lacoste Slim Fit Shirt',
      slug: 'lacoste-slim-fit-shirt',
      category: 'Shirts',
      image: '/images/p12.jpg',
      price: 110,
      countInStock: 6,
      brand: 'Lacoste',
      rating: 4.6,
      numReviews: 19,
      description: 'Slim fit shirt with signature embroidered logo',
    },
    {
      // _id: '13',
      name: 'Levi\'s Denim Shirt',
      slug: 'levis-denim-shirt',
      category: 'Shirts',
      image: '/images/p13.jpg',
      price: 70,
      countInStock: 15,
      brand: 'Levi\'s',
      rating: 4.2,
      numReviews: 14,
      description: 'Classic denim shirt with pearl snap buttons',
    },
    {
      // _id: '14',
      name: 'Calvin Klein Stretch Shirt',
      slug: 'calvin-klein-stretch-shirt',
      category: 'Shirts',
      image: '/images/p14.jpg',
      price: 80,
      countInStock: 10,
      brand: 'Calvin Klein',
      rating: 4.4,
      numReviews: 16,
      description: 'Stretch cotton blend for comfort and mobility',
    },
    // Pants (15-19)
    {
      // _id: '15',
      name: 'Levi\'s 501 Original Jeans',
      slug: 'levis-501-original-jeans',
      category: 'Pants',
      image: '/images/p15.jpg',
      price: 90,
      countInStock: 18,
      brand: 'Levi\'s',
      rating: 4.8,
      numReviews: 32,
      description: 'Iconic straight leg jeans with button fly',
    },
    {
      // _id: '16',
      name: 'Dockers Slim Fit Chinos',
      slug: 'dockers-slim-fit-chinos',
      category: 'Pants',
      image: '/images/p16.jpg',
      price: 65,
      countInStock: 14,
      brand: 'Dockers',
      rating: 4.3,
      numReviews: 21,
      description: 'Versatile slim fit chinos for work or casual wear',
    },
    {
      // _id: '17',
      name: 'Under Armour Golf Pants',
      slug: 'under-armour-golf-pants',
      category: 'Pants',
      image: '/images/p17.jpg',
      price: 80,
      countInStock: 12,
      brand: 'Under Armour',
      rating: 4.5,
      numReviews: 17,
      description: 'Performance golf pants with moisture-wicking technology',
    },
    {
      // _id: '18',
      name: 'Columbia Outdoor Pants',
      slug: 'columbia-outdoor-pants',
      category: 'Pants',
      image: '/images/p18.jpg',
      price: 75,
      countInStock: 16,
      brand: 'Columbia',
      rating: 4.6,
      numReviews: 20,
      description: 'Outdoor adventure pants with water-repellent finish',
    },
    {
      // _id: '19',
      name: 'Hugo Boss Dress Pants',
      slug: 'hugo-boss-dress-pants',
      category: 'Pants',
      image: '/images/p19.jpg',
      price: 150,
      countInStock: 8,
      brand: 'Hugo Boss',
      rating: 4.7,
      numReviews: 15,
      description: 'Premium wool blend dress pants for formal occasions',
    },
    // Joggers (20-24)
    {
      // _id: '20',
      name: 'Nike Tech Fleece Joggers',
      slug: 'nike-tech-fleece-joggers',
      category: 'Joggers',
      image: '/images/p20.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 26,
      description: 'Lightweight joggers with tapered fit and zippered pockets',
    },
    {
      // _id: '21',
      name: 'Adidas Tiro Joggers',
      slug: 'adidas-tiro-joggers',
      category: 'Joggers',
      image: '/images/p21.jpg',
      price: 55,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 31,
      description: 'Soccer-inspired joggers with ankle zips',
    },
    {
      // _id: '22',
      name: 'Champion Reverse Weave Joggers',
      slug: 'champion-reverse-weave-joggers',
      category: 'Joggers',
      image: '/images/p22.jpg',
      price: 60,
      countInStock: 18,
      brand: 'Champion',
      rating: 4.4,
      numReviews: 19,
      description: 'Classic reverse weave joggers with ribbed cuffs',
    },
    {
      // _id: '23',
      name: 'Puma Essential Joggers',
      slug: 'puma-essential-joggers',
      category: 'Joggers',
      image: '/images/p23.jpg',
      price: 45,
      countInStock: 25,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 22,
      description: 'Comfortable everyday joggers with drawstring waist',
    },
    {
      // _id: '24',
      name: 'Under Armour Rival Joggers',
      slug: 'under-armour-rival-joggers',
      category: 'Joggers',
      image: '/images/p24.jpg',
      price: 65,
      countInStock: 17,
      brand: 'Under Armour',
      rating: 4.5,
      numReviews: 24,
      description: 'Soft, mid-weight cotton blend joggers for training',
    },
    // Tracks (31-35)
    {
      // _id: '31',
      name: 'Nike Dri-FIT Track Pants',
      slug: 'nike-dri-fit-track-pants',
      category: 'Tracks',
      image: '/images/p31.jpg',
      price: 70,
      countInStock: 19,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 25,
      description: 'Moisture-wicking track pants for performance training',
    },
    {
      // _id: '32',
      name: 'Adidas 3-Stripe Track Pants',
      slug: 'adidas-3-stripe-track-pants',
      category: 'Tracks',
      image: '/images/p32.jpg',
      price: 65,
      countInStock: 23,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 29,
      description: 'Iconic 3-stripe track pants with ankle zips',
    },
    {
      // _id: '33',
      name: 'Puma T7 Track Pants',
      slug: 'puma-t7-track-pants',
      category: 'Tracks',
      image: '/images/p33.jpg',
      price: 60,
      countInStock: 21,
      brand: 'Puma',
      rating: 4.4,
      numReviews: 18,
      description: 'Retro-inspired track pants with contrast stripe',
    },
    {
      // _id: '34',
      name: 'Fila Vintage Track Pants',
      slug: 'fila-vintage-track-pants',
      category: 'Tracks',
      image: '/images/p34.jpg',
      price: 55,
      countInStock: 16,
      brand: 'Fila',
      rating: 4.3,
      numReviews: 15,
      description: 'Classic vintage-style track pants with logo embroidery',
    },
    {
      // _id: '35',
      name: 'Kappa Banda Track Pants',
      slug: 'kappa-banda-track-pants',
      category: 'Tracks',
      image: '/images/p35.jpg',
      price: 50,
      countInStock: 20,
      brand: 'Kappa',
      rating: 4.2,
      numReviews: 17,
      description: 'Slim fit track pants with iconic logo tape',
    },
    // T-shirts (26-30)
    {
      // _id: '26',
      name: 'Nike Dri-FIT T-Shirt',
      slug: 'nike-dri-fit-t-shirt',
      category: 'T-shirts',
      image: '/images/p26.jpg',
      price: 35,
      countInStock: 30,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 28,
      description: 'Performance t-shirt with moisture-wicking technology',
    },
    {
      // _id: '27',
      name: 'Adidas Trefoil T-Shirt',
      slug: 'adidas-trefoil-t-shirt',
      category: 'T-shirts',
      image: '/images/p27.jpg',
      price: 30,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 22,
      description: 'Classic cotton t-shirt with iconic trefoil logo',
    },
    {
      // _id: '28',
      name: 'Ralph Lauren Polo T-Shirt',
      slug: 'ralph-lauren-polo-t-shirt',
      category: 'T-shirts',
      image: '/images/p28.jpg',
      price: 45,
      countInStock: 18,
      brand: 'Ralph Lauren',
      rating: 4.6,
      numReviews: 19,
      description: 'Premium pima cotton t-shirt with embroidered logo',
    },
    {
      // _id: '29',
      name: 'Calvin Klein Slim Fit T-Shirt',
      slug: 'calvin-klein-slim-fit-t-shirt',
      category: 'T-shirts',
      image: '/images/p29.jpg',
      price: 40,
      countInStock: 22,
      brand: 'Calvin Klein',
      rating: 4.3,
      numReviews: 20,
      description: 'Slim fit t-shirt in soft cotton blend',
    },
    {
      // _id: '30',
      name: 'Tommy Hilfiger Logo T-Shirt',
      slug: 'tommy-hilfiger-logo-t-shirt',
      category: 'T-shirts',
      image: '/images/p30.jpg',
      price: 35,
      countInStock: 24,
      brand: 'Tommy Hilfiger',
      rating: 4.2,
      numReviews: 17,
      description: 'Classic t-shirt with signature logo across chest',
    },
    // Sweaters (36-40)
    {
      // _id: '36',
      name: 'Ralph Lauren Cable Knit Sweater',
      slug: 'ralph-lauren-cable-knit-sweater',
      category: 'Sweaters',
      image: '/images/p36.jpg',
      price: 125,
      countInStock: 10,
      brand: 'Ralph Lauren',
      rating: 4.7,
      numReviews: 16,
      description: 'Classic cable knit sweater in premium cotton',
    },
    {
      // _id: '37',
      name: 'Tommy Hilfiger V-Neck Sweater',
      slug: 'tommy-hilfiger-v-neck-sweater',
      category: 'Sweaters',
      image: '/images/p37.jpg',
      price: 90,
      countInStock: 14,
      brand: 'Tommy Hilfiger',
      rating: 4.5,
      numReviews: 18,
      description: 'Lightweight v-neck sweater with logo embroidery',
    },
    {
      // _id: '38',
      name: 'Lacoste Crew Neck Sweater',
      slug: 'lacoste-crew-neck-sweater',
      category: 'Sweaters',
      image: '/images/p38.jpg',
      price: 115,
      countInStock: 12,
      brand: 'Lacoste',
      rating: 4.6,
      numReviews: 15,
      description: 'Fine knit crew neck sweater with ribbed trim',
    },
    {
      // _id: '39',
      name: 'Calvin Klein Merino Wool Sweater',
      slug: 'calvin-klein-merino-wool-sweater',
      category: 'Sweaters',
      image: '/images/p39.jpg',
      price: 110,
      countInStock: 9,
      brand: 'Calvin Klein',
      rating: 4.4,
      numReviews: 13,
      description: 'Luxurious merino wool sweater for cold weather',
    },
    {
      // _id: '40',
      name: 'Hugo Boss Cashmere Blend Sweater',
      slug: 'hugo-boss-cashmere-blend-sweater',
      category: 'Sweaters',
      image: '/images/p40.jpg',
      price: 175,
      countInStock: 6,
      brand: 'Hugo Boss',
      rating: 4.8,
      numReviews: 12,
      description: 'Premium cashmere blend sweater with subtle logo detail',
    },
    // Shoes (41-45)
    {
      name: 'Nike Air Max 270',
      slug: 'nike-air-max-270',
      category: 'Shoes',
      image: '/images/p41.jpg',
      price: 150,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 35,
      description: 'Lifestyle sneakers with the first-ever Max Air unit designed specifically for all-day comfort',
    },
    {
      name: 'Adidas Ultra Boost',
      slug: 'adidas-ultra-boost',
      category: 'Shoes',
      image: '/images/p42.jpg',
      price: 180,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 42,
      description: 'Premium running shoes with responsive Boost technology',
    },
    {
      name: 'Puma RS-X',
      slug: 'puma-rs-x',
      category: 'Shoes',
      image: '/images/p43.jpg',
      price: 120,
      countInStock: 18,
      brand: 'Puma',
      rating: 4.7,
      numReviews: 28,
      description: 'Retro-inspired sneakers with chunky design',
    },
    {
      name: 'Nike Air Force 1',
      slug: 'nike-air-force-1',
      category: 'Shoes',
      image: '/images/p44.jpg',
      price: 100,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 38,
      description: 'Classic sneakers with timeless design',
    },
    {
      name: 'Adidas Stan Smith',
      slug: 'adidas-stan-smith',
      category: 'Shoes',
      image: '/images/p45.jpg',
      price: 90,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 32,
      description: 'Iconic tennis shoes with clean, minimalist design',
    },
    {
      // _id: '25',
      name: 'Nike Air Jordan T-Shirt',
      slug: 'nike-air-jordan-t-shirt',
      category: 'Shirts',
      image: '/images/p25.jpg',
      price: 85,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 20,
      description: 'Classic Air Jordan t-shirt with iconic logo',
    },
  ],
};
export default data;